// A curated set of common English words, 3–6 letters, used to validate
// matches in Gravity Word. Plain functional word-list data, not excerpted
// from any single copyrighted compilation.

const WORDS = `
ACE ACT ADD AGE AGO AID AIM AIR ALL AND ANT ANY APE ARC ARM ART ASH ASK ATE AWE AXE
BAD BAG BAN BAR BAT BAY BED BEE BEG BET BIG BIN BIT BOB BOG BOW BOX BOY BUD BUG BUN
BUS BUT BUY CAB CAN CAP CAR CAT COB COD COG CON COP COT COW COY CRY CUB CUE CUP CUT
DAB DAD DAM DAY DEN DEW DID DIE DIG DIM DIN DIP DOE DOG DOT DRY DUB DUE DUG DUO DYE
EAR EAT EGG EGO ELF ELK EMU END ERA EVE EWE EYE FAN FAR FAT FED FEE FEW FIG FIN FIR
FIT FIX FLY FOG FOR FOX FRY FUN FUR GAP GAS GAY GEL GEM GET GIG GIN GUM GUN GUT GUY
HAM HAT HAY HEN HER HEX HID HIM HIP HIS HIT HOG HOP HOT HUB HUG HUT ICE ICY ILL INK
INN ION ITS IVY JAM JAR JAW JAY JET JOB JOG JOY KEY KID KIN KIT LAB LAD LAG LAP LAW
LAY LEG LET LID LIE LIP LIT LOG LOT LOW MAD MAN MAP MAT MAY MEN MET MIX MOB MOM MOP
MUD MUG NAP NET NEW NOD NOR NOT NOW NUT OAK OAR ODD OFF OFT OIL OLD ONE OPT ORB OUR
OUT OWL OWN PAD PAL PAN PAT PAW PAY PEA PEG PEN PET PIE PIG PIN PIT POD POP POT PRO
PUB PUG PUN PUP PUT RAG RAM RAN RAP RAT RAW RAY RED RIB RID RIG RIM RIP ROB ROD ROT
ROW RUB RUG RUM RUN RYE SAD SAG SAP SAT SAW SAY SEA SEE SET SEW SHY SIN SIP SIR SIT
SIX SKI SKY SLY SOB SON SOW SOY SPA SPY SUB SUE SUM SUN SUP TAB TAG TAN TAP TAR TAX
TEA TEN TIE TIN TIP TOE TON TOO TOP TOY TRY TUB TUG TWO USE VAN VAT VET VOW WAG WAR
WAS WAX WAY WEB WED WET WHO WHY WIG WIN WIT WOK WON WOO WOW YAK YAM YES YET YOU ZAP
ZIP ZOO
ABLE ACID AGED ALSO AREA ARMY AWAY BABY BACK BAKE BALD BALL BAND BANK BARE BARK
BASE BATH BEAM BEAN BEAR BEAT BEEF BEEN BEER BELL BELT BEND BENT BEST BIKE BILL
BIRD BITE BLOW BLUE BOAT BODY BOIL BOLD BOLT BOND BONE BOOK BOOM BOOT BORE BORN
BOSS BOTH BOWL BULK BURN BUSH BUSY CAFE CAGE CAKE CALL CALM CAMP CARD CARE CARS
CASE CASH CAST CAVE CELL CHAT CHIP CITY CLAY CLIP CLUB COAL COAT CODE COIN COLD
COOK COOL COPE CORE CORN COST CREW CROP DARK DATA DATE DAWN DAYS DEAD DEAL DEAR
DEBT DEEP DEER DESK DIAL DICE DIET DIRT DISH DOCK DOES DONE DOOR DOSE DOVE DOWN
DRAW DREW DROP DRUM DUCK DULL DUMP DUST DUTY EACH EARN EASE EAST EASY EDGE EDIT
ELSE EVEN EVER EVIL EXAM EXIT FACE FACT FADE FAIL FAIR FALL FAME FARM FAST FATE
FEAR FEED FEEL FEET FELL FELT FILE FILL FILM FIND FINE FIRE FIRM FISH FIST FIVE
FLAG FLAT FLEW FLIP FLOW FOLD FOLK FOOD FOOL FOOT FORD FORM FORT FOUR FREE FROG
FROM FUEL FULL FUND GAIN GAME GANG GAPS GATE GAVE GAZE GEAR GENE GIFT GIRL GIVE
GLAD GLOW GOAL GOAT GOES GOLD GOLF GONE GOOD GRAB GRAY GREW GREY GRID GRIM GRIN
GRIP GROW GULF HAIR HALF HALL HAND HANG HARD HARM HATE HAVE HAWK HEAD HEAL HEAP
HEAR HEAT HELD HELL HELP HERB HERE HERO HIDE HIGH HILL HINT HIRE HOLD HOLE HOLY
HOME HOOK HOPE HORN HOST HOUR HUGE HUNT HURT HYMN ICON IDEA IDLE INCH INTO IRON
ITEM JAZZ JEAN JOIN JOKE JOLT JUMP JUNE JURY JUST KEEN KEEP KEPT KICK KIND KING
KISS KNEE KNEW KNIT KNOB KNOT KNOW LACE LACK LADY LAID LAKE LAMB LAMP LAND LANE
LAST LATE LAWN LAYS LEAD LEAF LEAN LEAP LEFT LEND LENS LESS LIFE LIFT LIKE LIME
LIMP LINE LINK LION LIPS LIST LIVE LOAD LOAN LOCK LOFT LOGO LONE LONG LOOK LOOP
LORD LOSE LOSS LOST LOUD LOVE LUCK LUNG MAIL MAIN MAKE MALE MARK MASK MASS MATE
MEAL MEAN MEAT MEET MELT MENU MERE MESH MESS MICE MILD MILE MILK MIND MINE MINT
MISS MIST MOLD MOOD MOON MORE MOSS MOST MOVE MUCH MUST NAIL NAME NAVY NEAR NECK
NEED NERD NEST NEWS NEXT NICE NINE NODE NOON NORM NOSE NOTE OAKS OATH OBEY ODOR
ONLY ONTO OPEN ORAL OVEN OVER PACE PACK PAGE PAID PAIN PAIR PALE PALM PARK PART
PAST PATH PEAK PEAR PICK PIER PILE PINE PINK PIPE PITY PLAN PLAY PLOT PLUG PLUM
POEM POET POLE POLL POND POOL POOR PORT POSE POST POUR PRAY PURE PUSH RACE RACK
RAGE RAID RAIL RAIN RANK RARE RATE READ REAL REAP REED REEF RELY REST RICE RICH
RIDE RING RISE RISK ROAD ROAM ROAR ROBE ROCK RODE ROLE ROLL ROOF ROOM ROOT ROPE
ROSE RUDE RUIN RULE RUNS RUSH RUST SACK SAFE SAGE SAID SAIL SALE SALT SAME SAND
SAVE SEAL SEAM SEAS SEAT SEED SEEK SEEM SEEN SELL SEND SENT SHED SHIP SHOE SHOP
SHOT SHOW SHUT SICK SIDE SIGH SIGN SILK SING SINK SITE SIZE SKIN SKIP SKIN SLAB
SLED SLID SLIM SLIP SLOT SLOW SNAP SOAP SOFT SOIL SOLD SOLE SOME SONG SOON SORT
SOUL SOUP SPAN SPIN SPOT STAR STAY STEM STEP STIR STOP SUCH SUIT SURE SWAM SWAN
SWIM TACO TAIL TAKE TALE TALK TALL TAME TANK TAPE TASK TEAM TEAR TECH TELL TEND
TENT TERM TEST TEXT THAN THAT THEM THEN THEY THIN THIS THUS TIDE TIDY TIME TINY
TIRE TOAD TOLD TOLL TONE TOOK TOOL TORN TOUR TOWN TOYS TRAM TRAP TREE TRIM TRIP
TRUE TUBE TUNE TURN TWIG TWIN TYPE UGLY UNIT UPON USED USER VAIN VAST VERY VEST
VIEW VOID VOTE WAGE WAIT WAKE WALK WALL WAND WANT WARD WARM WARN WASH WAVE WAYS
WEAK WEAR WEED WEEK WELL WENT WERE WEST WHAT WHEN WHIP WIDE WIFE WILD WILL WIND
WINE WING WIRE WISE WISH WITH WOLF WOOD WOOL WORD WORE WORK WORM WORN WRAP YARD
YEAR YOGA YOKE ZERO ZONE ZOOM
ABOUT ABOVE ADOPT ADULT AFTER AGAIN AGENT AGREE AHEAD ALARM ALBUM ALERT ALIEN
ALIKE ALIVE ALLOW ALONE ALONG ALTER AMONG ANGEL ANGER ANGLE ANGRY APART APPLE
APPLY APRON ARENA ARGUE ARISE ARRAY ASIDE ASSET AUDIO AUDIT AVOID AWAKE AWARD
AWARE BADGE BADLY BAKER BASIC BASIN BASIS BATCH BEACH BEARD BEGAN BEGIN BEGUN
BEING BELOW BENCH BERRY BIRTH BLACK BLADE BLAME BLANK BLAST BLEND BLESS BLIND
BLOCK BLOOD BLOOM BLOWN BLUNT BLUSH BOARD BOAST BOOST BOOTH BORED BORNE BOUND
BRAIN BRAND BRASS BRAVE BREAD BREAK BREED BRICK BRIDE BRIEF BRING BROAD BROKE
BROOK BROOM BROWN BRUSH BUILD BUILT BUNCH BURST CABIN CABLE CANDY CARGO CARRY
CATCH CAUSE CHAIN CHAIR CHALK CHAOS CHARM CHART CHASE CHEAP CHEAT CHECK CHEEK
CHEER CHESS CHEST CHIEF CHILD CHILL CHOSE CIVIC CIVIL CLAIM CLASS CLEAN CLEAR
CLERK CLICK CLIFF CLIMB CLOCK CLOSE CLOTH CLOUD CLOWN COACH COAST COVER CRACK
CRAFT CRASH CRAZY CREAM CREEK CREPT CRIME CRISP CROSS CROWD CROWN CRUDE CRUEL
CRUSH CURVE DAILY DELTA DENSE DEPTH DERBY DEVIL DIARY DIRTY DOUBT DOZEN DRAFT
DRAIN DRAMA DRANK DRAWN DREAM DRESS DRIED DRIFT DRILL DRINK DRIVE DROVE DRUNK
DUSTY EAGER EAGLE EARLY EARTH EIGHT ELBOW ELDER ELITE EMPTY ENJOY ENTER ENTRY
EQUAL ERROR EVENT EVERY EXACT EXIST EXTRA FABLE FAINT FAIRY FAITH FALSE FANCY
FATAL FAULT FAVOR FEAST FENCE FERRY FETCH FEVER FIBER FIELD FIFTH FIFTY FIGHT
FINAL FIRST FIXED FLAME FLASH FLEET FLESH FLOAT FLOOD FLOOR FLOUR FLUID FLUSH
FOCUS FORCE FORTH FORTY FORUM FOUND FRAME FRANK FRAUD FRESH FRONT FROST FROWN
FROZE FRUIT FULLY FUNNY GAUGE GHOST GIANT GIVEN GLAND GLARE GLASS GLOBE GLORY
GLOVE GOOSE GRACE GRADE GRAIN GRAND GRANT GRAPE GRASP GRASS GRAVE GREAT GREEN
GREET GRIEF GRILL GRIND GRIP GROSS GROUP GROVE GUARD GUESS GUEST GUIDE GUILD
GUILT HABIT HAPPY HARSH HASTE HASTY HATCH HAVEN HEARD HEART HEAVY HEDGE HENCE
HONEY HONOR HORSE HOTEL HOUSE HUMAN HUMOR HURRY IDEAL IMAGE IMPLY INNER INPUT
ISSUE IVORY JOINT JOLLY JOUST JOYED JUDGE JUICE JUMPY JUNGLE
KNIFE KNOCK KNOWN LABEL LABOR LARGE LASER LATER LAUGH LAYER LEARN LEAST LEAVE
LEGAL LEMON LEVEL LIGHT LIMIT LINEN LIVER LOCAL LOGIC LOOSE LOWER LOYAL LUCKY
LUNCH LYING MAGIC MAJOR MAKER MARCH MARRY MATCH MAYBE MAYOR MEDAL MEDIA MELON
MERCY MERIT MERRY METAL MIGHT MINOR MINUS MIXED MODEL MODEM MOIST MONEY MONTH
MORAL MOTOR MOUNT MOUSE MOUTH MOVED MOVIE MUSIC NAKED NASTY NEEDY NERVE NEVER
NEWLY NICHE NIGHT NOISE NORTH NOTED NOVEL NURSE OCCUR OCEAN OFFER OFTEN OLIVE
ONION OPERA ORBIT ORDER OTHER OUGHT OUTER OWNED OXIDE PAINT PANEL PANIC PAPER
PATCH PAUSE PEACE PEARL PHASE PHONE PHOTO PIANO PIECE PILOT PITCH PIVOT PIXEL
PLACE PLAIN PLANE PLANT PLATE PLAZA PLUMB POINT POPPY POUND POWER PRESS PRICE
PRIDE PRIME PRINT PRIOR PRIZE PROOF PROUD PROVE PULSE PUMPS PUNCH PUPIL PURSE
QUEEN QUERY QUEST QUICK QUIET QUITE QUOTE RADAR RADIO RAISE RALLY RANCH RANGE
RAPID RATIO REACH REACT READY REALM REBEL REFER RELAX REMIX REPLY RIDGE RIFLE
RIGHT RIGID RIVAL RIVER ROBOT ROCKY ROUGH ROUND ROUTE ROYAL RULER RUMOR RURAL
SADLY SALAD SAUCE SAUTE SCALE SCARE SCARF SCENE SCOPE SCORE SCOUT SENSE SERVE
SETUP SEVEN SHADE SHAKE SHALL SHAME SHAPE SHARE SHARK SHARP SHEEP SHEET SHELF
SHELL SHIFT SHINE SHIRT SHOCK SHONE SHOOT SHORE SHORT SHOUT SHOWN SHRUG SIGHT
SILLY SINCE SIXTH SIXTY SKILL SKULL SLATE SLEEP SLICE SLIDE SLOPE SMALL SMART
SMELL SMILE SMOKE SNAKE SNOW SOLAR SOLID SOLVE SORRY SOUND SOUTH SPACE SPARE
SPARK SPEAK SPEED SPELL SPEND SPENT SPICE SPIKE SPILL SPINE SPLIT SPOIL SPOKE
SPOON SPORT SQUAD STACK STAFF STAGE STAIN STAIR STAKE STALE STAND STARE START
STATE STEAK STEAM STEEL STEEP STEER STERN STICK STIFF STILL STING STOCK STONE
STOOD STORE STORM STORY STOVE STRAW STRIP STUCK STUDY STUFF STYLE SUGAR SUNNY
SUPER SWEAR SWEAT SWEET SWIFT SWING SWORD TABLE TAKEN TASTE TEACH TEARS THANK
THEFT THEIR THEME THERE THESE THICK THIEF THING THINK THIRD THOSE THREE THREW
THROW THUMB TIGER TIGHT TIRED TITLE TODAY TOOTH TOPIC TOTAL TOUCH TOUGH TOWEL
TOWER TOXIC TRACE TRACK TRADE TRAIL TRAIN TRAIT TRASH TREAT TREND TRIAL TRIBE
TRICK TRIED TROOP TRUCK TRULY TRUNK TRUST TRUTH TULIP TUTOR TWICE UNCLE UNDER
UNION UNITE UNTIL UPPER UPSET URBAN URGED USAGE USUAL VALID VALUE VAPOR VENUE
VIDEO VIRUS VISIT VITAL VIVID VOCAL VOICE VOTER WAGON WASTE WATCH WATER WAVES
WEIGH WEIRD WHALE WHEAT WHEEL WHERE WHICH WHILE WHITE WHOLE WHOSE WIDEN WIDOW
WIDTH WOMAN WOMEN WOODY WORLD WORRY WORSE WORST WORTH WOULD WOUND WOVEN WRIST
WRONG YACHT YIELD YOUNG YOUTH ZEBRA
`;

export const WORD_SET: ReadonlySet<string> = new Set(
  WORDS.split(/\s+/).map((w) => w.trim()).filter(Boolean)
);

export function isValidWord(word: string): boolean {
  return WORD_SET.has(word.toUpperCase());
}
